[build]
command = "netlify-lambda install && mkdir ./public"
functions = "functions"

[template.environment]
BOT_TOKEN = "Telegram bot token here"
OMDB_API_KEY = "OMDB api secret key here"

[[redirects]]
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"
